language: python
sudo: required


python:
  - 2.7
  - 3.5
  - 3.6

notifications:
  email:
    recipients:
    - steven.murray@curtin.edu.au

deploy:
  user: stevenjeanette
  on:
    tags: true
  provider: pypi
  password:
    secure: lAM0ScaCdOTbixtJf908INAKIpVCIPLSu4ZpqSxdp0zzMsTJJoTLo00wlmzzjeQDsxqgpiUIvjnwlpdur7Q+IPmwFa9hkg4VX4Mqe0keoDaoUQaUzpypZqYF0w4egVgc62NnXCGg3B/JuqUFuyM692uvmjvokGmadXLevXvPaxM=

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran-6

before_install:
  - sudo ln -s /usr/bin/gfortran-6 /usr/bin/gfortran

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis coverage coveralls

# command to run tests, e.g. python setup.py test
script:
  - tox
  - coverage report
#  - coverage run --source pydftools -m py.test
#  - coverage report -m

after_success:
  - coveralls
